# Generated by Django 6.0 on 2026-01-07 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.TextField(blank=True),
        ),
    ]
