# Generated by Django 6.0 on 2026-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
